#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

# Node LTS
image: cypress/base:16.13.0

pipelines:
  default:
    - parallel:
        - step:
            name: Build and test
            caches:
              - node
              - npm
              - cypress
            script:
              - yarn install
              - yarn build
              # - yarn lint
              - yarn test
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress